package com.bhgroup.pms.domain;

public enum AuditAction {
    USER_REGISTERED,
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAILED,
    USER_LOCKED_OUT,
    USER_LOGOUT,
    TOKEN_REFRESHED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    MFA_ENABLED,
    MFA_DISABLED,
    MFA_CHALLENGE_SUCCESS,
    MFA_CHALLENGE_FAILED
}
