import { apiClient } from "@/lib/api/client"
import { ApiError } from "@/lib/api/types"

export interface DynamicPricingConfigResponse {
  propertyId: string
  enabled: boolean
  minPrice: number | null
  maxPrice: number | null
  occupancyWindowDays: number
  occupancyMultiplierMin: number
  occupancyMultiplierMax: number
  leadTimeDays: number
  leadTimeMultiplier: number
}

export interface DynamicPricingConfigPayload {
  enabled: boolean
  minPrice: number | null
  maxPrice: number | null
  occupancyWindowDays: number
  occupancyMultiplierMin: number
  occupancyMultiplierMax: number
  leadTimeDays: number
  leadTimeMultiplier: number
}

/** How much real booking history the recommendation rests on. */
export type AiPricingConfidence = "LOW" | "MEDIUM" | "HIGH"

export type AiPricingReasonCode =
  | "LOW_FUTURE_OCCUPANCY"
  | "HIGH_FUTURE_OCCUPANCY"
  | "BELOW_HISTORICAL_OCCUPANCY"
  | "ABOVE_HISTORICAL_OCCUPANCY"
  | "SHORT_LEAD_TIME"
  | "LONG_LEAD_TIME"
  | "LOCAL_EVENT_CONFIGURED"
  | "INSUFFICIENT_HISTORY"
  | "WEEKEND_DEMAND_PATTERN"

export interface AiPricingReason {
  code: AiPricingReasonCode
  /** Deterministic Romanian copy generated by the backend, never raw model prose. */
  message: string
  indicator: string
  currentValue: number
  comparisonValue: number | null
  periodDays: number
}

/**
 * Same shape as {@link DynamicPricingConfigPayload} on purpose: an accepted
 * recommendation is applied by sending it straight to the update endpoint.
 */
export interface AiRecommendedPricingConfig {
  enabled: boolean
  minPrice: number | null
  maxPrice: number | null
  occupancyWindowDays: number
  occupancyMultiplierMin: number
  occupancyMultiplierMax: number
  leadTimeDays: number
  leadTimeMultiplier: number
}

/** The numbers the recommendation was computed from. */
export interface AiPricingMetrics {
  windowDays: number
  bookedNights: number
  windowNights: number
  /** Booked share of the window, 0–1. */
  occupancyRate: number
  averageDailyRate: number | null
  basePricePerNight: number | null
  seasonalRatesConfigured: number
  upcomingLocalEvents: number
}

export interface AiPricingRecommendationResponse {
  propertyId: string
  currency: string
  recommendation: AiRecommendedPricingConfig
  confidence: AiPricingConfidence
  summary: string
  reasons: AiPricingReason[]
  metricsUsed: AiPricingMetrics
  warnings: string[]
  missingData: string[]
  generatedAt: string
}

/** Thrown when a recommendation comes back addressed to another property. */
export const AI_RECOMMENDATION_PROPERTY_MISMATCH = "AI_RECOMMENDATION_PROPERTY_MISMATCH"

/**
 * Romanian message for a failed recommendation. Lives here rather than in the
 * hook so the toast and the inline error on the form say the same thing.
 */
export function aiRecommendationErrorMessage(error: unknown): string {
  if (error instanceof ApiError) {
    // 502 means the provider returned an invalid recommendation; 503 means
    // the provider is unavailable or not configured. Neither failure may
    // change the pricing form.
    if (error.status === 502) return "Recomandarea AI a fost respinsă ca invalidă"
    if (error.status === 503) return "Recomandarea AI nu este disponibilă acum"
    if (error.status === 403) return "Nu ai permisiunea de a genera recomandări de preț"
    if (error.status === 404) return "Proprietatea nu a fost găsită"
    return error.message
  }
  if (error instanceof Error && error.message === AI_RECOMMENDATION_PROPERTY_MISMATCH) {
    return "Recomandarea primită era pentru altă proprietate și a fost ignorată"
  }
  return "Generarea recomandării AI a eșuat"
}

export interface LocalEventResponse {
  id: string
  city: string | null
  propertyId: string | null
  propertyName: string | null
  label: string
  startDate: string
  endDate: string
  priceMultiplier: number
  createdAt: string
}

export interface LocalEventPayload {
  city?: string
  propertyId?: string
  label: string
  startDate: string
  endDate: string
  priceMultiplier: number
}

export interface NightlyPriceBreakdown {
  date: string
  baseRate: number
  occupancyFactor: number
  commerciallyBookedNights: number
  sellableNights: number
  leadTimeFactor: number
  eventFactor: number
  rateBeforeClamp: number
  rateAfterClamp: number
}

export interface DynamicPriceBreakdownResponse {
  available: boolean
  unavailableReason: string | null
  checkInDate: string
  checkOutDate: string
  nights: number
  nightlyBreakdown: NightlyPriceBreakdown[]
  subtotal: number | null
  extraGuestFee: number | null
  cleaningFee: number | null
  discountPercent: number | null
  discountAmount: number | null
  totalAmount: number | null
  currency: string
}

export interface BreakdownParams {
  checkIn: string
  checkOut: string
  guests: number
}

function buildQuery(params: Record<string, string | number | undefined>) {
  const query = new URLSearchParams()
  Object.entries(params).forEach(([key, value]) => {
    if (value !== undefined && value !== "") {
      query.set(key, String(value))
    }
  })
  const qs = query.toString()
  return qs ? `?${qs}` : ""
}

export const pricingApi = {
  getConfig: (propertyId: string) =>
    apiClient.get<DynamicPricingConfigResponse>(`/properties/${propertyId}/pricing/config`),

  updateConfig: (propertyId: string, payload: DynamicPricingConfigPayload) =>
    apiClient.put<DynamicPricingConfigResponse>(`/properties/${propertyId}/pricing/config`, payload),

  // Advisory: this changes nothing server-side. Applying the suggestion is
  // still a separate updateConfig call the admin has to trigger.
  getAiRecommendation: (propertyId: string) =>
    apiClient.post<AiPricingRecommendationResponse>(
      `/properties/${propertyId}/pricing/ai-recommendation`
    ),

  getBreakdown: (propertyId: string, params: BreakdownParams) =>
    apiClient.get<DynamicPriceBreakdownResponse>(
      `/properties/${propertyId}/pricing/breakdown${buildQuery({
        checkIn: params.checkIn,
        checkOut: params.checkOut,
        guests: params.guests,
      })}`
    ),

  // The backend does not combine city + propertyId in one request: passing
  // propertyId makes it ignore city entirely. Callers must issue two
  // separate requests (one per scope) and merge the results themselves.
  listEventsForProperty: (propertyId: string) =>
    apiClient.get<LocalEventResponse[]>(`/local-events${buildQuery({ propertyId })}`),

  listEventsForCity: (city: string) =>
    apiClient.get<LocalEventResponse[]>(`/local-events${buildQuery({ city })}`),

  createEvent: (payload: LocalEventPayload) =>
    apiClient.post<LocalEventResponse>("/local-events", payload),

  deleteEvent: (id: string) => apiClient.delete<void>(`/local-events/${id}`),
}
